### ISSUE TITLE
Comments killing Cards

### ISSUE THREAD

**Issue by cwhicher** [repositive/report-issues#2]
I just left a comment on a dataset (4ccc4079-a5c7-4fd0-ab25-7d20022e6034). When I press the tick after    commenting the comment doesn't appear. If I then navigate away from the card, and then return to the card - the card no longer works!! :-(

**Comment by timini** [comment]
please stop breaking the platform

**Comment by timini** [comment]
@cwhicher Found the cause of this, was a missing package that has been readded now. Have deployed a fix
